const colors = {
    mainBgColor: "#FF3C3C",
    vibrantBlue: "#0000ff",
    vibrantRed: "#FF0000",
    cardBgColor: "#7ddffa",
    gameBgColor: [
        "#F7F7F7",
        "#FCFCFC",
        "#FFF9E7",
        "#FFF8E6",
        "#F3E9DA",
        "#FFF2E6",
        "#E6F0FB",
        "#E6FFFF",
        "#E6F9FF",
        "#E6F0FB",
        "#E0F9FF",
        "#F1F9E5",
        "#E8FFF9",
        "#E6F9ED",
        "#E5F7E2",
        "#E6F9E0",
        "#FDF8E6",
        "#FFFFE6",
        "#FFFFE0",
        "#FEE8E7",
        "#FFE5E7",
        "#FFE5E2",
        "#FFE5DA",
        "#FFE5E0",
        "#FFE0DA",
        "#F3F0FF",
        "#E6F0FF",
        "#E6F6F0",
    ],
};

export default colors;
